### ISSUE TITLE
你好我有个问题想咨询一下

### ISSUE THREAD

**Issue by zzzlw** [JeasonWong/NewsTemplate#2]
我最近想实现文章详情视频滑动可见自动播放以及暂停，现在想象是在图片上贴片原生视频控件，请问你在使用ObservableWebView时候可以准确定位哪一张图片滑动可见吗？

**Comment by JeasonWong** [comment]
@zzzlw 可以通过高度做

**Comment by zzzlw** [comment]
额，再请教一下，怎么才能让原生控件与ObservableWebView 里面的图片一起滚动呢。

**Comment by JeasonWong** [comment]
ObservableScrollView里的LinearLayout可以组合嵌套ObservableWebView和其他原生控件啊。。没太理解你的意思

**Comment by zzzlw** [comment]
我的意思是LinearLayout覆盖ObservableWebView之上，当图片划可见之后，然后LinearLayout里的视频可见，盖住ObservableWebView里面的那张图，与ObservableWebView一起滚动。

**Comment by JeasonWong** [comment]
照你的思路走也可以，ScrollView滑动的时候通知LinearLayout动态更改marginTop，从0往负数变。

**Comment by zzzlw** [comment]
多谢，我去实践一下。

**Comment by zzzlw** [comment]
@JeasonWong 多谢，我实现了WebView里面是可以addview的。
